version: "3.7"
services:
  php:
    image: php:fpm-alpine
    container_name: php
    restart: always  
    volumes:
      - "./html:/usr/share/nginx/html:ro"
    networks:
      - live002_network
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    restart: always  
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./html:/usr/share/nginx/html:ro"
    depends_on:
      - php
    networks:
      - live002_network
networks:
  live002_network:
    driver: bridge